/* $0 build step: bundle the ES-module frontend (src/) into a single same-origin
 * script, carefind.bundle.js, that carefind.html loads with a plain <script src>.
 *
 * Why: it keeps the "one HTML file + a backend" deploy story (the bundle is a build
 * artifact, not hand-authored), removes all inline business logic from the HTML so
 * the CSP can drop 'unsafe-inline' for scripts, and gives the page testable modules.
 *
 * Determinism: esbuild is pinned to an exact version and run with fixed options, so
 * `npm run build` reproduces the committed carefind.bundle.js byte-for-byte. CI
 * rebuilds and fails on any diff (see .github/workflows/ci.yml), which guarantees the
 * committed artifact always matches src/.
 */
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url)));
const banner = `/* CareFind bundle — GENERATED by \`npm run build\` from src/. Do not edit by hand.\n` +
  `   Edit src/*.js and rebuild; CI verifies this file matches the source. */`;

await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  charset: 'utf8',
  legalComments: 'none',
  minify: false, // readable, reviewable diffs; size is handled by ETag caching
  banner: { js: banner },
  outfile: 'carefind.bundle.js',
});

console.log('Built carefind.bundle.js from src/main.js');
