/* $0 build step: bundle the ES-module frontend (src/) into a single same-origin
 * script, innetwork.bundle.js, that innetwork.html loads with a plain <script src>.
 *
 * Why: it keeps the "one HTML file + a backend" deploy story (the bundle is a build
 * artifact, not hand-authored), removes all inline business logic from the HTML so
 * the CSP can drop 'unsafe-inline' for scripts, and gives the page testable modules.
 *
 * Determinism: esbuild is pinned to an exact version and run with fixed options, so
 * `npm run build` reproduces the committed innetwork.bundle.js byte-for-byte. CI
 * rebuilds and fails on any diff (see .github/workflows/ci.yml), which guarantees the
 * committed artifact always matches src/.
 */
import { build } from 'esbuild';
const banner =
  `/* InNetwork bundle — GENERATED by \`npm run build\` from src/. Do not edit by hand.\n` +
  `   Edit src/*.js and rebuild; CI verifies this file matches the source. */`;

await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  charset: 'utf8',
  legalComments: 'none',
  // Minify for the wire: esbuild is deterministic (pinned version + fixed options), so the
  // committed artifact still reproduces byte-for-byte and CI's diff gate holds. The readable,
  // reviewable source lives in src/ (and innetwork.logic.js, served separately) — the bundle
  // is a generated artifact, so shipping it minified cuts transfer + parse/eval cost.
  minify: true,
  banner: { js: banner },
  outfile: 'innetwork.bundle.js',
});

console.log('Built innetwork.bundle.js from src/main.js');
